apiVersion: apps/v1
kind: Deployment
metadata:
  name: bft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bft
  template:
    metadata:
      labels:
        app: bft
    spec:
      containers:
      - image: okteto.dev/bft:latest
        name: bft
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "eff193c4-3c1f-4722-9201-72e34120aa13"
        - name: Vless_Path
          value: "/fwrgjyu"
        - name: Vmess_UUID
          value: "eff193c4-3c1f-4722-9201-72e34120aa13"
        - name: Vmess_Path
          value: "/gvf5htd"
        - name: Share_Path
          value: "/v2link"
